name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=counter tests/

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.projectKey=your-sonar-project-key
            -Dsonar.organization=your-sonar-organization
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: your-dockerhub-username/object-counter:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set Up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Kubernetes context setup
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Deploy to Kubernetes (DEV)
        run: |
          helm upgrade --install object-counter charts/ \
            --set image.repository=your-dockerhub-username/object-counter \
            --set image.tag=${{ github.sha }} \
